// Phase 0.5 — IGNORE. Generates a per-repo `.understandignore` file
// (mirrors UA's `.understandignore`) by reading the project's
// `.gitignore` and prepending language-grouped test/build defaults.
// The file lives at `wiki/code_wiki/<repo>/.understand/.understandignore`
// and is consulted by the scanner's filter pass to skip files the
// user wants excluded from analysis.
//
// Pattern format: one glob per line, `#` for comments. Lines starting
// with `!` re-include a previously-excluded pattern (negation).
//
// We intentionally do NOT shell out to `gitignore` parser crates —
// the input is a small file and the matching logic is delegated to
// the scanner (which already walks the tree and can check each
// candidate path against the list of glob literals). This keeps
// the dependency surface small.

use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};

/// Default ignore patterns grouped by ecosystem. These mirror
/// UA's `generate-ignore.mjs` defaults.
const DEFAULT_IGNORE_PATTERNS: &[&str] = &[
    "# Generated by llm_wiki code-wiki pipeline",
    "# Lines starting with ! re-include a previously-excluded path.",
    "",
    "# --- Build outputs ---",
    "dist/",
    "build/",
    "out/",
    "target/",          // Rust
    ".next/",            // Next.js
    ".nuxt/",            // Nuxt
    ".output/",          // Nuxt 3
    ".svelte-kit/",      // SvelteKit
    "bin/",
    "obj/",
    "",
    "# --- Vendored dependencies ---",
    "node_modules/",
    "vendor/",
    "Pods/",
    "Carthage/",
    ".gradle/",
    "",
    "# --- Cache & test artifacts ---",
    ".cache/",
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".tox/",
    ".coverage",
    "coverage/",
    "htmlcov/",
    ".nyc_output/",
    "",
    "# --- Lock files (excluded by default to keep graph focused on source) ---",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "composer.lock",
    "Gemfile.lock",
    "Pipfile.lock",
    "poetry.lock",
    "uv.lock",
    "bun.lockb",
    "",
    "# --- IDE & OS ---",
    ".idea/",
    ".vscode/",
    ".DS_Store",
    "Thumbs.db",
    "*.swp",
    "*.swo",
    "",
    "# --- Generated files ---",
    "*.min.js",
    "*.min.css",
    "*.lock",
    "*.generated.*",
    "*_pb2.py",          // protobuf python
    "*_pb2_grpc.py",
];

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct IgnoreConfig {
    /// Patterns read from `<project_root>/.gitignore` (verbatim).
    pub gitignore_patterns: Vec<String>,
    /// The default patterns we always add (idempotent).
    pub default_patterns: Vec<String>,
}

/// Generate the `.understandignore` content for a project. Reads the
/// project's `.gitignore` and combines it with the defaults. If
/// `.understandignore` already exists, returns its existing content
/// (the user owns it once created).
pub fn generate_understandignore_inner(project_root: &Path) -> Result<String, String> {
    let target = project_root
        .join(".understand-anything")
        .join(".understandignore");
    if target.is_file() {
        return fs::read_to_string(&target)
            .map_err(|e| format!("read existing .understandignore: {e}"));
    }

    let gitignore_path = project_root.join(".gitignore");
    let mut gitignore_block = String::new();
    if gitignore_path.is_file() {
        let raw = fs::read_to_string(&gitignore_path)
            .map_err(|e| format!("read .gitignore: {e}"))?;
        // Strip blank lines and comments for clarity.
        let patterns: Vec<&str> = raw
            .lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        if !patterns.is_empty() {
            gitignore_block.push_str("\n# --- From .gitignore ---\n");
            for p in patterns {
                gitignore_block.push_str(p);
                gitignore_block.push('\n');
            }
        }
    }

    let mut out = String::new();
    for p in DEFAULT_IGNORE_PATTERNS {
        out.push_str(p);
        out.push('\n');
    }
    out.push_str(&gitignore_block);

    Ok(out)
}

/// Read the `.understandignore` content if present, otherwise return
/// an empty Vec (caller treats as no exclusions).
pub fn read_understandignore(project_root: &Path) -> Vec<String> {
    let target = project_root
        .join(".understand-anything")
        .join(".understandignore");
    let Ok(raw) = fs::read_to_string(&target) else { return Vec::new() };
    raw.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|s| s.to_string())
        .collect()
}

/// Test whether a relative path matches any of the supplied ignore
/// patterns. Patterns are simple `dir/`, `*.ext`, or literal name
/// matches. No support for `**` globs — our patterns don't use them
/// and adding a full glob engine is overkill for the v1.
pub fn is_ignored(rel_path: &str, patterns: &[String]) -> bool {
    let p = rel_path.replace('\\', "/");
    for raw in patterns {
        let pat = raw.trim();
        if pat.is_empty() || pat.starts_with('#') { continue; }
        if let Some(stripped) = pat.strip_prefix('!') {
            // Negation: re-include. We don't support nested exclusion
            // resolution, so once a negation matches, we mark as
            // not-ignored. (This is good enough for our default
            // patterns which don't have any negations.)
            if glob_match(stripped, &p) { return false; }
            continue;
        }
        if glob_match(pat, &p) { return true; }
    }
    false
}

/// Tiny glob matcher. Supports:
///   - `dir/` — matches any file/dir under `dir/`
///   - `*.ext` — matches any file ending in `.ext`
///   - `name` — exact match on any path segment
///   - `path/with/slashes` — prefix match
fn glob_match(pattern: &str, path: &str) -> bool {
    if let Some(dir) = pattern.strip_suffix('/') {
        // Directory match: any descendant or the dir itself.
        return path == dir || path.starts_with(&format!("{dir}/"));
    }
    if let Some(ext) = pattern.strip_prefix("*.") {
        return path.ends_with(&format!(".{ext}"));
    }
    if pattern.contains('/') {
        return path == pattern || path.starts_with(&format!("{pattern}/"));
    }
    // Bare name: match any segment equal to it.
    path.split('/').any(|seg| seg == pattern)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn fixture() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let mut f = std::fs::File::create(dir.path().join(".gitignore")).unwrap();
        writeln!(f, "*.log").unwrap();
        writeln!(f, "/build_artifacts/").unwrap();
        writeln!(f, "# comment").unwrap();
        drop(f);
        dir
    }

    #[test]
    fn generate_combines_defaults_and_gitignore() {
        let dir = fixture();
        let out = generate_understandignore_inner(dir.path()).unwrap();
        assert!(out.contains("node_modules/"), "default pattern missing");
        assert!(out.contains("dist/"), "default pattern missing");
        assert!(out.contains("*.log"), ".gitignore pattern missing");
        assert!(out.contains("build_artifacts/"), ".gitignore pattern missing");
        assert!(!out.contains("# comment"), ".gitignore comment leaked into output");
    }

    #[test]
    fn generate_returns_existing_when_present() {
        let dir = fixture();
        let target = dir.path().join(".understand-anything");
        std::fs::create_dir_all(&target).unwrap();
        let mut f = std::fs::File::create(target.join(".understandignore")).unwrap();
        writeln!(f, "# user-owned").unwrap();
        writeln!(f, "user-pattern/").unwrap();
        drop(f);
        let out = generate_understandignore_inner(dir.path()).unwrap();
        assert_eq!(out, "# user-owned\nuser-pattern/\n");
    }

    #[test]
    fn is_ignored_matches_directory_prefix() {
        let patterns = vec!["node_modules/".to_string()];
        assert!(is_ignored("node_modules/foo/index.js", &patterns));
        assert!(is_ignored("node_modules", &patterns));
        assert!(!is_ignored("src/foo.ts", &patterns));
    }

    #[test]
    fn is_ignored_matches_glob_extension() {
        let patterns = vec!["*.log".to_string()];
        assert!(is_ignored("debug.log", &patterns));
        assert!(is_ignored("logs/today.log", &patterns));
        assert!(!is_ignored("logs/today.txt", &patterns));
    }

    #[test]
    fn is_ignored_matches_bare_name() {
        let patterns = vec![".DS_Store".to_string()];
        assert!(is_ignored(".DS_Store", &patterns));
        assert!(is_ignored("sub/.DS_Store", &patterns));
        assert!(!is_ignored("src/foo.ts", &patterns));
    }

    #[test]
    fn is_ignored_skips_comments_and_blanks() {
        let patterns = vec![
            "# comment".to_string(),
            "".to_string(),
            "node_modules/".to_string(),
        ];
        assert!(is_ignored("node_modules/foo.js", &patterns));
        assert!(!is_ignored("src/foo.js", &patterns));
    }

    #[test]
    fn read_understandignore_returns_patterns() {
        let dir = fixture();
        let target = dir.path().join(".understand-anything");
        std::fs::create_dir_all(&target).unwrap();
        let mut f = std::fs::File::create(target.join(".understandignore")).unwrap();
        writeln!(f, "# header").unwrap();
        writeln!(f, "").unwrap();
        writeln!(f, "*.tmp").unwrap();
        drop(f);
        let pats = read_understandignore(dir.path());
        assert_eq!(pats, vec!["*.tmp".to_string()]);
    }
}
